export const channels = {
    CREATE_CHANNEL_SAGA: 'CREATE_CHANNEL_SAGA',
    SUCCESS_CREATE_CHANNEL: 'SUCCESS_CREATE_CHANNEL',
    ERROR_CREATE_CHANNEL: 'ERROR_CREATE_CHANNEL',

    FETCH_CHANNELS_SAGA: 'FETCH_CHANNELS_SAGA',
    FETCH_CHANNELS: 'FETCH_CHANNELS',
    ERROR_FETCH_CHANNELS: 'ERROR_FETCH_CHANNELS'
};

export const users = {
    FETCH_USERS_SAGA: 'FETCH_USERS_SAGA',
    FETCH_USERS: 'FETCH_USERS',
    ERROR_FETCH_USERS: 'ERROR_FETCH_USERS'
};

export const register = {
    REGISTER_USER_SAGA: 'REGISTER_USER_SAGA',
    SUCCESS_REGISTER_USER: 'SUCCESS_REGISTER_USER',
    ERROR_REGISTER_USER: 'ERROR_REGISTER_USER',
};

export const user = {
    FETCH_USER: 'FETCH_USER',
    ERROR_FETCH_USER: 'ERROR_FETCH_USER',

    JOIN_USER_CHANNEL: 'JOIN_USER_CHANNEL',
    ERROR_JOIN_USER_CHANNEL: 'ERROR_JOIN_USER_CHANNEL',
};

export const auth = {
    LOGIN_USER: 'LOGIN_USER',
    ERROR_LOGIN_USER: 'ERROR_LOGIN_USER',
    LOGIN_USER_SAGA: 'LOGIN_USER_SAGA',

    LOGOUT_USER: 'LOGOUT_USER',
    LOGOUT_USER_SAGA: 'LOGOUT_USER_SAGA',

    CHECK_IS_LOGIN: 'CHECK_IS_LOGIN',
    CHECK_IS_LOGIN_SAGA: 'CHECK_IS_LOGIN_SAGA'
};

export const messages = {
    FETCH_MESSAGES_SAGA: 'FETCH_MESSAGES_SAGA',
    FETCH_MESSAGES: 'FETCH_MESSAGES',
    ERROR_FETCH_MESSAGES: 'ERROR_FETCH_MESSAGES',

    SEND_MESSAGES_SAGA: 'SEND_MESSAGES_SAGA',
    SEND_MESSAGES: 'SEND_MESSAGES',
    ERROR_SEND_MESSAGES: 'ERROR_SEND_MESSAGES',
};

export const settings = {
    CHANGE_USERNAME_SAGA: 'CHANGE_USERNAME_SAGA',
    CHANGE_USERNAME: 'CHANGE_USERNAME',
    ERROR_CHANGE_USERNAME: 'ERROR_CHANGE_USERNAME'
};